name: lightsketchCloud
tags:
  app: lightsketchCloud

network:
  vpc:
    natGatewaySubnetName: Public
    maxAzs: 3

  subnets:
    # Private subnet
    - cidrMask: 21
      name: Private
      subnetType: PRIVATE_WITH_EGRESS
    # Client UI subnet
    - cidrMask: 21
      name: Public
      subnetType: PUBLIC

compute:
  ecs:
    app:
      amis:
        us-east-1: ami-03a32d185474e28bc
        eu-west-1: ami-003c39e7a86e90450


