aws_account: "188775091215"
aws_region: us-west-2

network:
  vpc:
    cidr: 10.1.0.0/16

compute:
  ecs:
    app:
      repo_arn: "arn:aws:ecr:us-east-1:188775091215:repository/lightsketch"
      image_tag: "latest"
      port: 7861
      minimum_containers: 1
      maximum_containers: 10
      base_memory: 10000
      cuda: 1
      ec2_keypair: dev